// <auto-generated />
using System;
using CallTree.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTree.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CallTreeDbContext))]
    partial class CallTreeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CallTree.Domain.Calls.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceClassification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("StartedAt");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("CallTree.Domain.Calls.CallLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HangupInitiator")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCallerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SipCallId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.ToTable("CallLeg");
                });

            modelBuilder.Entity("CallTree.Domain.Calls.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelLayout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .IsUnique();

                    b.ToTable("Recording");
                });

            modelBuilder.Entity("CallTree.Domain.Calls.CallLeg", b =>
                {
                    b.HasOne("CallTree.Domain.Calls.Call", null)
                        .WithMany("Legs")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CallTree.Domain.Calls.Recording", b =>
                {
                    b.HasOne("CallTree.Domain.Calls.Call", null)
                        .WithOne("Recording")
                        .HasForeignKey("CallTree.Domain.Calls.Recording", "CallId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CallTree.Domain.Calls.Call", b =>
                {
                    b.Navigation("Legs");

                    b.Navigation("Recording");
                });
#pragma warning restore 612, 618
        }
    }
}
